version: '3'
services:
  reverse-proxy:
    image: traefik
    command: --api --docker --logLevel="INFO"
    restart: unless-stopped
    container_name: weird_traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: weird_postgres
    env_file:
      - env_dev
    expose:
      - "5432"
  web:
    build: .
    container_name: weird_web
    restart: unless-stopped
    volumes:
      - ./django:/django
    ports:
      - "8000:80"
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - env_dev
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.priority=10"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.backend=web"
      - "traefik.port=80"